analy/urls.py
from django.urls import path
from . import views

app_name = 'analy'
urlpatterns = [
    path('upload/', views.upload, name='upload'),
]

interest/urls.py
from django.urls import path
from . import views

app_name = 'interest'
urlpatterns = [
    path('interest/', views.interest, name='interest'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('keyword/', views.keyword, name='keyword'),
    path('video/', views.video, name='video'),
    path('theme/', views.theme, name='theme'),
    path('fifth/', views.fifth, name='fifth'),
    path('chart/', views.chart, name='chart'),
]

team/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name='door.html'), name='home'),
    path('admin/', admin.site.urls),
    url('first/', TemplateView.as_view(template_name='first.html'), name='home1'),
    url('second/', TemplateView.as_view(template_name='second.html'), name='home2'),
    url('third/', TemplateView.as_view(template_name='third.html'), name='home3'),
    url('fourth/', TemplateView.as_view(template_name='fourth.html'), name='home4'),
    path('analy/', include('analy.urls')),
    path('search/', include('search.urls')),
    path('interest/', include('interest.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>웹과 음악 사이</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <script
            src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.4.0/wavesurfer.min.js"></script>

    <style>
        body {
        background-image: url(/static/img/back.jpg);
        background-size: 100% 100%;
        background-attachment: fixed;
        overflow-y:hidden
        }
        .mydiv-top {
        height: 10px;
        }
        .door1 {
        height: 90px;
        text-align: center;
        vertical-align: middle;
        padding: 0.6em 0 0;
        }
        .keyword-table {
        opacity: 0.75;
        background-color: #FFFFF0;
        }
        .mytext {
        color: #FFFFF0;
        text-align: center;
        opacity: 0.8;
        }
        .here {
        overflow-y:scroll;
        width:1050px;
        height:600px;
        }
        .here::-webkit-scrollbar {
        display: none;
        }
        nav {
        opacity: 0.8;
        }
        #sidebar {
        background-color: #212529;
        }
    </style>
</head>

<body>
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar" >
                <div style="text-align: center; height: 100px; padding-top: 15px; font-size: 25px;">
                    <a href="{% url 'home' %}" class="logo" style="color: #60a5f7; font-weight: bold">웹과 음악 사이</a>
                </div>
                <ul class="list-unstyled components mb-5" style="font-weight: bold ">
                    <li class="active">
                        <a href="{% url 'home1' %}"><span class="fa fa-upload mr-3"></span> 음악 분석</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home2' %}"><span class="fa fa-search mr-3"></span> 키워드 검색</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home3' %}"><span class="fa fa-youtube mr-3"></span> 동영상 검색</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home4' %}"><span class="fa fa-film mr-3"></span> 테마별 검색</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'search:fifth' %}"><span class="fa fa-list mr-3"></span> 장르별 인기차트</a>
                    </li>
                </ul>
        </nav>
            <div id="content" class="p-4 p-md-5 pt-5">
                <div class="mydiv-top"></div>
                {% block container %}
                {% endblock %}
                </div>
            </div>
    </div>
    <script src="/static/js/jquery.min.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="/static/js/popper.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="/static/js/bootstrap.min.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="/static/js/main.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js"
            data-cf-settings="2e70319bb3298c022c929462-|49" defer=""></script>
</body>
</html>

team/templates/door.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

<style>
    #a-here {
    font-size: 20px;
    }
</style>

<div class="mydiv-top"></div>
<div style="height: 150px;"></div>
<h2 class="mb-4 door1 mytext">대문</h2>
<div style="text-align: center;">
    <a href="{% url 'interest:interest' %}" id="a-here" style="color: #ebe939">오늘의 인기차트 100</a>
</div>
{% endblock %}

team/templates/fifth.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}


<h3 class="mb-4 mytext">인기차트</h3>
{% for int in ints %}
    <div>
        <form action="{% url 'search:chart' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input name="number" type="hidden" value="{{ int }}">{{ int }}</input>
            <input type="submit" value="검색" style="text-align: center;" >
        </form>
    </div>
{% endfor %}


{% endblock %}

team/templates/first.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}
<h2 class="mb-4 mytext">내음악 분석하기</h2>

<div style="text-align: center;">
    <form action="{% url 'analy:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input  id="input-audio-file" type="file" name="audio"
                accept=".wav,.mp3,.aac,.ogg,.wma,.flac,.alac,.aiff,audio/*"
                multiple="multiple" >
        <input type="submit" value="업로드">
    </form>
</div>
{% endblock %}

team/templates/fourth.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}


<h2 class="mb-4 mytext">영화 OST 검색하기</h2>
<p style="text-align: center;">※최대 50가지를 알려드리며, 키워드에 따라 시간이 소요될 수 있습니다.</p>

<div style="text-align: center;">
    <form action="{% url 'search:theme' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="movie" style="text-align: center;">
        <input type="submit" value="검색" style="text-align: center;">
    </form>

</div>


<h2 class="mb-4 mytext">드라마 OST 검색하기</h2>
<p style="text-align: center;">※최대 50가지를 알려드리며, 키워드에 따라 시간이 소요될 수 있습니다.</p>

<div style="text-align: center;">
    <form action="{% url 'search:theme' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="drama" style="text-align: center;">
        <input type="submit" value="검색" style="text-align: center;">
    </form>

</div>


<h2 class="mb-4 mytext">뮤지컬 OST 검색하기</h2>
<p style="text-align: center;">※최대 50가지를 알려드리며, 키워드에 따라 시간이 소요될 수 있습니다.</p>

<div style="text-align: center;">
    <form action="{% url 'search:theme' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="musical" style="text-align: center;">
        <input type="submit" value="검색" style="text-align: center;">
    </form>

</div>

{% endblock %}

team/templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

<style>
    th, td {
    text-align: center;
    font-size: 15px;
    }
</style>

<h2 class="mb-4 mytext">{{ date }} 인기 차트</h2>

{% if charts %}

    <div class="container here">
        <table class="table table-hover keyword-table here">
            <thead>
                <tr>
                    <th scope="col" style="width: 10%">순위</th>
                    <th scope="col" style="width: 60%">노래</th>
                    <th scope="col" style="width: 30%">가수</th>
                </tr>
            </thead>
            <tbody>
                {% for chart in charts %}
                <tr>
                    <th>{{ forloop.counter }}위</th>
                    <td>{{ chart.title }}</td>
                    <td>{{ chart.artist }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endif %}

{% endblock %}

team/templates/second.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}


<h2 class="mb-4 mytext">키워드로 검색하기</h2>
<p style="text-align: center;">※최대 50가지를 알려드리며, 키워드에 따라 시간이 소요될 수 있습니다.</p>

<div style="text-align: center;">
    <form action="{% url 'search:keyword' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" style="text-align: center;">
    <input type="submit" value="검색" style="text-align: center;">
</form>

</div>

{% endblock %}

team/templates/third.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}
<h2 class="mb-4 mytext">동영상 검색하기</h2>

<div style="text-align: center;">
    <form action="{% url 'search:video' %}" method="post">
        {% csrf_token %}
        <input type="text" name="video">
        <input type="submit" value="검색">
    </form>
</div>
{% endblock %}